# Generated by Django 4.2.13 on 2025-05-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_tag', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
            ],
        ),
    ]
